Traceback (most recent call last):
  File "/home/ubuntu/mlops-zoomcamp-hw/02-experiment-tracking/homework-wandb/train.py", line 68, in <module>
    run_train()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/mlops-zoomcamp-hw/02-experiment-tracking/homework-wandb/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2734, in use_artifact
    raise ValueError(
ValueError: You must pass an artifact name (e.g. "pedestrian-dataset:v1"), an instance of `wandb.Artifact`, or `wandb.Api().artifact()` to `use_artifact`
Traceback (most recent call last):
  File "/home/ubuntu/mlops-zoomcamp-hw/02-experiment-tracking/homework-wandb/train.py", line 68, in <module>
    run_train()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/mlops-zoomcamp-hw/02-experiment-tracking/homework-wandb/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2734, in use_artifact
    raise ValueError(
ValueError: You must pass an artifact name (e.g. "pedestrian-dataset:v1"), an instance of `wandb.Artifact`, or `wandb.Api().artifact()` to `use_artifact`